// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/1/2025, 5:21:53 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/app/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/frontend/plugins/**/*.{js,ts,mjs}","/app/frontend/composables/**/*.{js,ts,mjs}","/app/frontend/utils/**/*.{js,ts,mjs}","/app/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;